Vagrant.configure("2") do |config|
config.vm.define :streama do |streama|
streama.vm.box = "bento/centos-7.8"
streama.vm.network :private_network, ip: "192.168.50.11"
streama.vm.provision "shell", path: "scriptstreama.sh"
streama.vm.provision "file", source: "dato1.txt" , destination: "/tmp/dato1.txt"
streama.vm.provision "shell", path: "scriptstreama1.sh"
streama.vm.provision "file", source: "dato2.txt" , destination: "/tmp/dato2.txt"
streama.vm.provision "shell", path: "scriptstreama2.sh"
streama.vm.hostname = "streama"
end

config.vm.define :firewall do |firewall|
firewall.vm.box = "bento/centos-7.8"
firewall.vm.network :public_network, :bridge=>"eth0", ip: "192.168.1.100"
firewall.vm.network :private_network, ip: "192.168.50.10"
firewall.vm.provision "shell", path: "scriptfirewall.sh"
firewall.vm.hostname = "firewall"
end
end

