Vagrant.configure("2") do |config|
	config.vm.define :rest do |rest|
		rest.vm.box = "bento/centos-7.8"
		rest.vm.network :private_network, ip: "192.168.50.2"
		rest.vm.hostname = "rest"
		rest.vm.provider "virtualbox" do |v|
			v.memory = 512
		end
	end
end
